#/usr/bin/python3

''' Task Description

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

14/01/2021 '''

def fibo(n):
   if n <= 1:
       return n
   else:
       return(fibo(n-1) + fibo(n-2))

list_of_fibo = []
for num in range(100000):
   list_of_fibo.append(fibo(num))
   if list_of_fibo[num] > 4000000:
       break

total_sum = 0
for num in list_of_fibo:
    if num % 2 == 0:
        total_sum += num

print(total_sum)